CREATE DATABASE Minions

USE Minions

CREATE TABLE Minions(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(20) NOT NULL,
	Age INT
);

CREATE TABLE Towns(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50)
);

ALTER TABLE Minions
ADD TownId INT CONSTRAINT FK_Minions_Towns FOREIGN KEY(TownId) REFERENCES Towns(Id);


